# Uncomment the next line to define a global platform for your project
platform :osx, '10.13'

target 'GitHubSearchApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubSearchApp
  pod 'CocoaReactComponentKit'
  pod 'SDWebImage'
  pod 'SnapKit'
  pod 'Moya'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
end
